apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: personal-web-page-tls
  namespace: public
spec:
  secretName: personal-web-page-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pavel-usanli.online