apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - metallb.yaml
  - metallb-config.yaml
  - traefik.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - nfs-provisioner.yaml