---
adguard_dns_port: 53
adguard_web_port: 80
adguard_install_dir: /opt/AdGuardHome
adguard_version: "0.107.75"
adguard_username: admin
adguard_password: ""
adguard_tls_enabled: true
adguard_tls_domain: "adguard.internal.pavel-usanli.online"
letsencrypt_email: ""
adguard_cert_path: "/etc/letsencrypt/live/adguard.internal.pavel-usanli.online/fullchain.pem"
adguard_key_path: "/etc/letsencrypt/live/adguard.internal.pavel-usanli.online/privkey.pem"