apiVersion: v1
kind: Service
metadata:
  name: crowdsec-appsec
  namespace: crowdsec
spec:
  selector:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/component: agent
  ports:
    - name: appsec
      port: 7422
      targetPort: 7422