apiVersion: v1
kind: Service
metadata:
  name: crowdsec-appsec
  namespace: crowdsec
spec:
  selector:
    k8s-app: crowdsec
    type: appsec
    version: v1
  ports:
    - name: appsec
      port: 7422
      targetPort: 7422
