apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
  namespace: crowdsec
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: crowdsec-secrets
    creationPolicy: Owner
  data:
    - secretKey: bouncer-api-key
      remoteRef:
        key: crowdsec-secrets
        property: bouncer-api-key
    - secretKey: webui-machine-id
      remoteRef:
        key: crowdsec-secrets
        property: webui-machine-id
    - secretKey: webui-password
      remoteRef:
        key: crowdsec-secrets
        property: webui-password
    - secretKey: enrollment-key
      remoteRef:
        key: crowdsec-secrets
        property: enrollment-key