apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shopify-gpt-assistant
  namespace: public
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: shopify-gpt-assistant-secrets
    creationPolicy: Owner
  data:
    - secretKey: SHOPIFY_API_KEY
      remoteRef:
        key: shopify-gpt-assistant-secrets
        property: api-key
    - secretKey: SHOPIFY_API_SECRET
      remoteRef:
        key: shopify-gpt-assistant-secrets
        property: api-secret
    - secretKey: DATABASE_URL
      remoteRef:
        key: shopify-gpt-assistant-secrets
        property: database-url
