---
pgadmin_email: ""
pgadmin_password: ""
pgadmin_postgres_host: "192.168.1.4"
pgadmin_postgres_port: 5432
pgadmin_tls_enabled: true
pgadmin_tls_domain: "pgadmin.internal.pavel-usanli.online"
letsencrypt_email: ""