apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-secret
  namespace: kube-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: crowdsec-bouncer-secret
    creationPolicy: Owner
  data:
    - secretKey: bouncer-api-key
      remoteRef:
        key: crowdsec-secrets
        property: bouncer-api-key