apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - personal-web-page
  - mite-assistant-mcp
  - capacity-planner
  - shopify-gpt-assistant
  - bunker-game-app
  - google-assistant-mcp
  - nocobase
