apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - metallb.yaml
  - metallb-config.yaml
  - traefik-config.yaml
  - nfs-provisioner.yaml
  - external-secrets.yaml
  - external-secrets-config.yaml
  - apps.yaml