apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-web-page
  namespace: public
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: personal-web-page
  template:
    metadata:
      labels:
        app: personal-web-page
    spec:
      automountServiceAccountToken: false
      containers:
        - name: personal-web-page
          image: ghcr.io/kalpak44/kalpak44:9045bcc
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
              ephemeral-storage: 50Mi
            limits:
              memory: 64Mi
              ephemeral-storage: 100Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
