apiVersion: apps/v1
kind: Deployment
metadata:
  name: sablier
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sablier
  template:
    metadata:
      labels:
        app: sablier
    spec:
      serviceAccountName: sablier
      containers:
        - name: sablier
          image: sablierapp/sablier:1.10.1
          args:
            - start
            - --provider.name=kubernetes
          ports:
            - containerPort: 10000