apiVersion: apps/v1
kind: Deployment
metadata:
  name: lex-bg-connector
  namespace: private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lex-bg-connector
  template:
    metadata:
      labels:
        app: lex-bg-connector
    spec:
      automountServiceAccountToken: false
      containers:
        - name: lex-bg-connector
          image: ghcr.io/kalpak44/lex-bg-connector:ed7a325
          ports:
            - containerPort: 3200
          env:
            - name: PRELOAD
              value: "true"
            - name: PRELOAD_PATH
              value: /data
            - name: DELAY_MS
              value: "1500"
            - name: PRELOAD_CRON
              value: "0 0 1 1 *"
            - name: PRELOAD_MAX_AGE_DAYS
              value: "1500"
          volumeMounts:
            - name: preload-data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
              ephemeral-storage: 64Mi
            limits:
              cpu: 500m
              memory: 2Gi
              ephemeral-storage: 256Mi
      volumes:
        - name: preload-data
          persistentVolumeClaim:
            claimName: lex-bg-connector-data
