apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playwright-mcp-output
  namespace: private
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
