---
- name: Apply netplan
  ansible.builtin.command: netplan apply

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted

- name: Save iptables
  ansible.builtin.command: netfilter-persistent save

- name: Restart ntopng
  ansible.builtin.systemd:
    name: ntopng
    state: restarted