all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    k3s:
      vars:
        ansible_user: ubuntu
      hosts:
        prod-k3s-1:
          ansible_host: 192.168.1.110
        prod-k3s-2:
          ansible_host: 192.168.1.111

    prod_lxc:
      vars:
        ansible_user: root
      hosts:
        prod-lb:
          ansible_host: 192.168.1.109

    prod_vm:
      vars:
        ansible_user: ubuntu
      hosts:
        prod-nfs:
          ansible_host: 192.168.1.108