apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ciela-mcp-secrets
  namespace: private
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: ciela-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: CIELA_USERNAME
      remoteRef:
        key: ciela-mcp-secrets
        property: ciela-username
    - secretKey: CIELA_PASSWORD
      remoteRef:
        key: ciela-mcp-secrets
        property: ciela-password