apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ciela-mcp
  namespace: private
spec:
  entryPoints:
    - private-web-secure
  routes:
    - match: Host(`ciela-mcp.internal.pavel-usanli.online`)
      kind: Rule
      services:
        - name: ciela-mcp
          port: 8811
  tls:
    certResolver: cloudflare