apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nocobase
  namespace: public
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: nocobase-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: nocobase-secrets
        property: db-user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: nocobase-secrets
        property: db-password
    - secretKey: APP_KEY
      remoteRef:
        key: nocobase-secrets
        property: app-key