apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nocobase
  namespace: public
spec:
  entryPoints:
    - public-web-secure
  routes:
    - match: Host(`nocobase.pavel-usanli.online`)
      kind: Rule
      services:
        - name: nocobase
          port: 80
  tls:
    certResolver: cloudflare