---
vault_version: "2.0.1"
vault_install_dir: /opt/vault
vault_data_dir: /opt/vault/data
vault_config_dir: /etc/vault.d
vault_api_port: 8200
vault_cluster_port: 8201
vault_username: ""
vault_password: ""
k3s_api_host: "192.168.1.110"
k3s_api_port: "6443"
vault_tls_enabled: true
vault_tls_domain: "vault.internal.pavel-usanli.online"
vault_cert_path: "/etc/vault.d/tls/cert.pem"
vault_key_path: "/etc/vault.d/tls/key.pem"
vault_addr: "{{ 'https' if vault_tls_enabled else 'http' }}://127.0.0.1:{{ vault_api_port }}"
