apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-web-ui-secrets
  namespace: private
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: crowdsec-web-ui-secrets
    creationPolicy: Owner
  data:
    - secretKey: CROWDSEC_USER
      remoteRef:
        key: crowdsec-secrets
        property: webui-machine-id
    - secretKey: CROWDSEC_PASSWORD
      remoteRef:
        key: crowdsec-secrets
        property: webui-password