apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-web-ui-data
  namespace: private
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi