apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mite-assistant-mcp
  namespace: public
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: mite-assistant-mcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: MITE_BASE_URL
      remoteRef:
        key: mite-assistant-mcp-secrets
        property: mite-url