---
- name: Restart Redis
  ansible.builtin.systemd:
    name: redis-server
    state: restarted

- name: Restart redis-commander
  ansible.builtin.systemd:
    name: redis-commander
    state: restarted