apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingressroute.yaml

namespace: public

configMapGenerator:
  - name: capacity-planner-html
    files:
      - index.html